# GitHub Labels Configuration
# This file defines the standard labels for this repository
# Use with github-label-sync or similar tools to apply these labels

# Priority Labels
- name: "priority: critical"
  color: "b60205"
  description: "Critical issue that blocks releases or causes data loss"

- name: "priority: high"
  color: "d93f0b"
  description: "High priority issue that should be addressed soon"

- name: "priority: medium"
  color: "fbca04"
  description: "Medium priority issue"

- name: "priority: low"
  color: "0e8a16"
  description: "Low priority issue"

# Type Labels
- name: "bug"
  color: "d73a4a"
  description: "Something isn't working"

- name: "enhancement"
  color: "a2eeef"
  description: "New feature or request"

- name: "documentation"
  color: "0075ca"
  description: "Improvements or additions to documentation"

- name: "question"
  color: "d876e3"
  description: "Further information is requested"

- name: "security"
  color: "b60205"
  description: "Security vulnerability or concern"

- name: "performance"
  color: "fbca04"
  description: "Performance improvement"

- name: "refactor"
  color: "e99695"
  description: "Code refactoring"

- name: "test"
  color: "c2e0c6"
  description: "Related to testing"

# Status Labels
- name: "status: needs-triage"
  color: "ededed"
  description: "Needs initial review and assignment"

- name: "status: accepted"
  color: "0e8a16"
  description: "Issue/PR has been accepted"

- name: "status: in-progress"
  color: "fbca04"
  description: "Currently being worked on"

- name: "status: on-hold"
  color: "fef2c0"
  description: "Work paused, waiting for dependencies"

- name: "status: needs-review"
  color: "0052cc"
  description: "Waiting for code review"

- name: "status: needs-testing"
  color: "1d76db"
  description: "Needs testing before merge"

- name: "status: blocked"
  color: "b60205"
  description: "Blocked by external dependencies"

- name: "status: wontfix"
  color: "ffffff"
  description: "This will not be worked on"

- name: "status: duplicate"
  color: "cfd3d7"
  description: "This issue or pull request already exists"

- name: "status: invalid"
  color: "e4e669"
  description: "This doesn't seem right"

# Component Labels
- name: "component: frontend"
  color: "006b75"
  description: "Frontend related changes"

- name: "component: backend"
  color: "5319e7"
  description: "Backend related changes"

- name: "component: api"
  color: "0052cc"
  description: "API related changes"

- name: "component: database"
  color: "1d76db"
  description: "Database related changes"

- name: "component: ci/cd"
  color: "0e8a16"
  description: "CI/CD pipeline changes"

- name: "component: dependencies"
  color: "0366d6"
  description: "Dependency updates"

# Effort Labels
- name: "effort: small"
  color: "c2e0c6"
  description: "Small effort (< 1 day)"

- name: "effort: medium"
  color: "fef2c0"
  description: "Medium effort (1-3 days)"

- name: "effort: large"
  color: "f9d0c4"
  description: "Large effort (> 3 days)"

# Special Labels
- name: "good first issue"
  color: "7057ff"
  description: "Good for newcomers"

- name: "help wanted"
  color: "008672"
  description: "Extra attention is needed"

- name: "breaking change"
  color: "b60205"
  description: "Introduces breaking changes"

- name: "needs reproduction"
  color: "fef2c0"
  description: "Bug report needs reproduction steps"

- name: "stale"
  color: "ededed"
  description: "Issue/PR has been inactive for a while"
